/*
 * Copyright 2026 MARLINK TRADING SRL (YounndAI)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// v1.D.5 — bumped 2 → 3 with the addition of the LYT_PRIMER section
// (agents.md `## Vault primer` between LYT_PRIMER_BEGIN/END markers) and
// the `## Vault Primer` transclusion in lyt-overview.md. Older v2 agents.md
// files without LYT_PRIMER markers stay untouched on regen (no surprise-
// edit) — only NEW files (via `getAgentsMdContent` / `scaffold/init.ts`)
// get the full v3 template.
export const AGENTS_MD_TEMPLATE_VERSION = 3;

export const MESH_CONTEXT_AUTO_BANNER =
  "<!-- AUTO-REGENERATED by `lyt vault regen-context`. Edits to this file are overwritten. -->";

// Delimiters marking the auto-regenerated "Installed patterns + skills" section in
// agents.md. The regen flows (pattern link/unlink, vault sync-metadata --apply)
// replace ONLY the content between these markers; the rest of agents.md is user-
// editable. Matches the priming-file transclusion pattern from 7A.
export const AGENTS_MD_PATTERNS_BEGIN = "<!-- LYT_PATTERNS_BEGIN -->";
export const AGENTS_MD_PATTERNS_END = "<!-- LYT_PATTERNS_END -->";

// v1.D.5 — delimiters for the agents.md `## Vault primer` section that
// points handlers at the `.lyt/primers/` directory + the `lyt primer
// --scope vault` regen verb. Same regen contract as LYT_PATTERNS: only
// the content between markers is replaced. NEW agents.md files (via
// `getAgentsMdContent`) include the markers + populated section; EXISTING
// v2 files without the markers stay untouched on regen.
export const AGENTS_MD_PRIMER_BEGIN = "<!-- LYT_PRIMER_BEGIN -->";
export const AGENTS_MD_PRIMER_END = "<!-- LYT_PRIMER_END -->";

export interface LytOverviewInput {
  vaultName: string;
  desc: string | null | undefined;
  owner: string;
}

export function getLytOverviewContent(input: LytOverviewInput): string {
  const desc = (input.desc ?? "").trim();
  const lines: string[] = [
    `# ${input.vaultName}`,
    ``,
    `## What this vault is`,
    ``,
    desc.length > 0
      ? desc
      : `_(Add a description here. Lyt scaffolded this section once at \`lyt vault init\` and never touches it again — it is yours to evolve.)_`,
    ``,
    `## Owner`,
    ``,
    input.owner,
    ``,
    `## Mesh Context`,
    ``,
    `![[.lyt/mesh-context]]`,
    ``,
    // v1.D.5 — additive `## Vault Primer` section AFTER `## Mesh Context`
    // per OD-4 default. Transcludes the markdown emitted by `lyt primer
    // --scope vault` so handlers opening lyt-overview.md in Obsidian see
    // the primer's hot keywords / active arcs / recent activity / top lanes
    // inline. The transclusion target may not exist on a fresh vault — in
    // that case Obsidian renders the embed as an empty placeholder; run
    // `lyt primer --scope vault --target <vault-name>` to populate it.
    `## Vault Primer`,
    ``,
    `![[.lyt/primers/vault-primer]]`,
    ``,
  ];
  return lines.join("\n");
}

export interface InstalledPatternSummary {
  id: string;
  name: string;
  version: string;
  verbIds: readonly string[];
  // Skill slugs that wrap this pattern's verbs (e.g., ["/lyt-plan", "/lyt-retro"]).
  // Optional — when omitted, the listing shows pattern + verbs without skill mapping.
  skills?: readonly string[] | undefined;
}

export interface AgentsMdInput {
  vaultName: string;
  // OPTIONAL — when present, the "Installed patterns + skills" section is populated
  // between the LYT_PATTERNS delimiters. When omitted/empty, the section shows the
  // empty-state placeholder.
  installedPatterns?: readonly InstalledPatternSummary[] | undefined;
}

export function getAgentsMdContent(input: AgentsMdInput): string {
  const patternsBlock = renderInstalledPatternsSection(input.installedPatterns);
  const primerBlock = renderInstalledPrimerSection(input.vaultName);
  return [
    `# Working with Lyt in this vault (for AI agents)`,
    ``,
    `<!-- @AGENT_TEMPLATE version=${AGENTS_MD_TEMPLATE_VERSION} -->`,
    ``,
    `This vault is a Lyt Vault, part of a federated mesh. Read this file before editing.`,
    ``,
    `## What this vault is`,
    ``,
    `\`${input.vaultName}\` — see [lyt-overview.md](./lyt-overview.md) for identity + mesh context.`,
    ``,
    `## Commands you can run`,
    ``,
    `- \`lyt vault info <name>\` — show this vault's metadata`,
    `- \`lyt vault list\` — show every registered vault on this machine`,
    `- \`lyt mesh status\` — show the federation graph`,
    `- \`lyt mesh init --from <manifest>\` — bulk-init a mesh from a YON manifest`,
    `- \`lyt vault regen-context <name>\` — rewrite \`.lyt/mesh-context.md\` from current edge state`,
    `- \`lyt vault sync-metadata --vault <name> [--apply]\` — push vault.yon metadata to GitHub (dry-run default)`,
    `- \`lyt primer --scope vault --target <name>\` — regenerate the vault primer (hot keywords + arcs + recent activity)`,
    `- \`lyt federation canvas\` / \`lyt mesh canvas --mesh <name>\` — emit Obsidian Canvas visualisations`,
    `- \`lyt pattern list\` / \`lyt pattern verbs <name>\` / \`lyt pattern run <p> <v> ...\` — manage operational patterns`,
    `- \`lyt help <topic>\` — full help surface (try \`lyt help patterns\` or \`lyt help skills\`)`,
    ``,
    `## How to read this vault`,
    ``,
    `- \`.lyt/vault.yon\` — this vault's identity + mesh edges (parent, share_with, topics)`,
    `- \`.lyt/mesh-context.md\` — auto-regenerated mesh context (transcluded into \`lyt-overview.md\`)`,
    `- \`.lyt/primers/\` — agent-priming markdown (committed by default; regenerated by \`lyt primer\`)`,
    `- \`.lyt/canvases/\` — Obsidian Canvas visualisations of federation + mesh graphs (committed; regenerated by \`lyt federation canvas\` + \`lyt mesh canvas\`)`,
    `- \`.obsidian/\` — Obsidian config (committed)`,
    `- \`notes/\` — Figments (markdown notes) live here`,
    `- \`Patterns/\` — symlinks to installed Lyt patterns (machine-local; gitignored)`,
    ``,
    `## Etiquette`,
    ``,
    `- Tag new Figments with \`tags:\` frontmatter — the federated index uses them.`,
    `- Use \`[[wikilinks]]\` for cross-Figment + cross-vault references.`,
    `- Never edit \`.lyt/indexes/*.db\` (libSQL derived state at \`.lyt/indexes/{lyt,audit,provenance}.db\` post-v1.A.2c DB SPLIT, regenerated by \`lyt vault rebuild-index\` from YON ledger SoT in \`.lyt/ledgers/\`).`,
    `- Never \`git add -A\` — name the paths.`,
    ``,
    `## Vault primer`,
    ``,
    `${AGENTS_MD_PRIMER_BEGIN}`,
    primerBlock,
    `${AGENTS_MD_PRIMER_END}`,
    ``,
    `## Installed patterns + skills`,
    ``,
    `${AGENTS_MD_PATTERNS_BEGIN}`,
    patternsBlock,
    `${AGENTS_MD_PATTERNS_END}`,
    ``,
  ].join("\n");
}

function renderInstalledPatternsSection(
  installed: readonly InstalledPatternSummary[] | undefined,
): string {
  if (!installed || installed.length === 0) {
    return `_(No patterns linked into this vault yet. Run \`lyt pattern list\` to see what's installed at \`~/lyt/patterns/\`, then \`lyt pattern link <name> --vault <this-vault>\` to link them. Or run \`lyt vault adopt <path>\` / \`lyt vault join <path>\` — both auto-rebuild symlinks for every installed pattern.)_`;
  }
  const lines: string[] = [];
  lines.push(`This vault has the following Lyt patterns linked at \`Patterns/\`:`, ``);
  for (const p of installed) {
    const verbs = p.verbIds.join(", ");
    if (p.skills && p.skills.length > 0) {
      lines.push(`- **${p.id}@${p.version}** (verbs: ${verbs}) → skills: ${p.skills.join(", ")}`);
    } else {
      lines.push(`- **${p.id}@${p.version}** (verbs: ${verbs})`);
    }
  }
  lines.push(
    ``,
    `Run \`lyt help patterns\` for the full pattern catalog. Run \`lyt pattern verbs <name>\` for a pattern's verb list.`,
  );
  return lines.join("\n");
}

// Regenerate ONLY the LYT_PATTERNS section of an existing agents.md, leaving the rest
// of the file (which the user may have edited) intact. If the markers aren't present
// (older v1 template), the entire file is rewritten via getAgentsMdContent.
export function regenInstalledPatternsSection(
  existingContent: string,
  vaultName: string,
  installed: readonly InstalledPatternSummary[],
): string {
  const beginIdx = existingContent.indexOf(AGENTS_MD_PATTERNS_BEGIN);
  const endIdx = existingContent.indexOf(AGENTS_MD_PATTERNS_END);
  if (beginIdx < 0 || endIdx < 0 || endIdx <= beginIdx) {
    return getAgentsMdContent({ vaultName, installedPatterns: installed });
  }
  const before = existingContent.slice(0, beginIdx + AGENTS_MD_PATTERNS_BEGIN.length);
  const after = existingContent.slice(endIdx);
  const middle = "\n" + renderInstalledPatternsSection(installed) + "\n";
  return before + middle + after;
}

// v1.D.5 — render the content of the `## Vault primer` section that lives
// between the LYT_PRIMER markers. The content is a static pointer to the
// `.lyt/primers/` directory + the `lyt primer` regen verb — the actual
// primer markdown lives in `.lyt/primers/{scope}-primer.md` and is
// transcluded into lyt-overview.md via `![[.lyt/primers/vault-primer]]`.
// Putting a pointer (not the full primer text) in agents.md keeps the
// file scannable for agents while preserving the SoT in the primer file.
function renderInstalledPrimerSection(vaultName: string): string {
  return [
    `_The primer files at \`.lyt/primers/\` hold hot keywords + active arcs + recent activity + top lanes for this vault and mesh. Read them as a fast on-ramp before deeper exploration._`,
    ``,
    `Regenerate with:`,
    ``,
    `- \`lyt primer --scope vault --target ${vaultName}\` → \`.lyt/primers/vault-primer.md\``,
    `- \`lyt primer --scope mesh --target <mesh-name>\` → \`<mesh-main-vault>/.lyt/primers/mesh-primer.md\``,
    `- \`lyt primer --scope federation\` → \`<federation-or-first-vault>/.lyt/primers/federation-primer.md\``,
  ].join("\n");
}

// v1.D.5 — regenerate ONLY the LYT_PRIMER section of an existing
// agents.md. Mirror of `regenInstalledPatternsSection`. If markers are
// absent (older v2 file), return the existing content UNCHANGED — do
// NOT surprise-edit user-edited agents.md by auto-injecting the new
// section (per "What was decided" §8 of the v1.D.5 brief + global
// Rule #9 don't-add-what-wasn't-asked).
//
// To opt an existing v2 file into v3, either delete `agents.md` (next
// regen recreates from the v3 template via getAgentsMdContent) or hand-
// edit the file to include the LYT_PRIMER markers around an empty
// section (next regen populates).
export function regenInstalledPrimerSection(existingContent: string, vaultName: string): string {
  const beginIdx = existingContent.indexOf(AGENTS_MD_PRIMER_BEGIN);
  const endIdx = existingContent.indexOf(AGENTS_MD_PRIMER_END);
  if (beginIdx < 0 || endIdx < 0 || endIdx <= beginIdx) {
    return existingContent;
  }
  const before = existingContent.slice(0, beginIdx + AGENTS_MD_PRIMER_BEGIN.length);
  const after = existingContent.slice(endIdx);
  const middle = "\n" + renderInstalledPrimerSection(vaultName) + "\n";
  return before + middle + after;
}

export function getNotesIndexContent(vaultName: string): string {
  return [
    `# Index`,
    ``,
    `Starter Figment for \`${vaultName}\`. Replace with your own first note, or delete it.`,
    ``,
    `## A few wikilink prompts`,
    ``,
    `- [[notes/welcome]]`,
    `- [[notes/inbox]]`,
    `- [[notes/decisions]]`,
    ``,
    `These targets do not exist yet — click any of them in Obsidian to create the file.`,
    ``,
  ].join("\n");
}
