/*
 * Copyright 2026 MARLINK TRADING SRL (YounndAI)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { buildFrontmatter } from "./contract.js";
import { renderTemplate } from "./render.js";

// v1.D.5 — bumped 2 → 3 with the addition of the LYT_PRIMER section
// (agents.md `## Vault primer` between LYT_PRIMER_BEGIN/END markers) and
// the `## Vault Primer` transclusion in lyt-overview.md. Older v2 agents.md
// files without LYT_PRIMER markers stay untouched on regen (no surprise-
// edit) — only NEW files (via `getAgentsMdContent` / `scaffold/init.ts`)
// get the full v3 template.
//
// COUPLED CONSTANT SEE ALSO (bump ALL three when bumping this value):
//   - yon/vault.ts  `template_version` @META — uses the SAME integer (both
//     describe the same scaffold-file-set generation; see VaultDoc.templateVersion).
//   - scaffold/init.ts `writeVaultYon` — passes this value as both
//     `agentTemplateVersion` AND `templateVersion` to renderVaultYon.
export const AGENTS_MD_TEMPLATE_VERSION = 3;

export const MESH_CONTEXT_AUTO_BANNER =
  "<!-- AUTO-REGENERATED by `lyt vault regen-context`. Edits to this file are overwritten. -->";

// Delimiters marking the auto-regenerated "Installed patterns + skills" section in
// agents.md. The regen flows (pattern link/unlink, vault sync-metadata --apply)
// replace ONLY the content between these markers; the rest of agents.md is user-
// editable. Matches the priming-file transclusion pattern from 7A.
export const AGENTS_MD_PATTERNS_BEGIN = "<!-- LYT_PATTERNS_BEGIN -->";
export const AGENTS_MD_PATTERNS_END = "<!-- LYT_PATTERNS_END -->";

// v1.D.5 — delimiters for the agents.md `## Vault primer` section that
// points handlers at the `.lyt/primers/` directory + the `lyt primer
// --scope vault` regen verb. Same regen contract as LYT_PATTERNS: only
// the content between markers is replaced. NEW agents.md files (via
// `getAgentsMdContent`) include the markers + populated section; EXISTING
// v2 files without the markers stay untouched on regen.
export const AGENTS_MD_PRIMER_BEGIN = "<!-- LYT_PRIMER_BEGIN -->";
export const AGENTS_MD_PRIMER_END = "<!-- LYT_PRIMER_END -->";

// Phase B (UNIT 1 — C2 sentinel-wiring) — fixed scaffold timestamp.
//
// The priming builders (getLytOverviewContent / getAgentsMdContent) now emit a
// real frontmatter block via the contract SoT (buildFrontmatter) carrying
// `lyt-scaffold: true`, so the g6 gate (util/indexable.ts SCAFFOLD_RE) FTS-
// excludes these Lyt-authored seed files. Because these are SCAFFOLD seeds (not
// user Figments) and the regen chokepoint (flows/agents-md-regen.ts) rewrites
// the whole file when markers are absent, the frontmatter MUST be deterministic
// — a wall-clock `created`/`modified` would (a) churn the file on every regen
// and (b) break the regen-idempotency contract (priming.test.ts). A fixed epoch
// sentinel timestamp keeps the emitted bytes stable + honest: scaffold seeds are
// not authored at a meaningful instant, so `created == modified == epoch` is the
// truthful value, not a fabricated "now".
const SCAFFOLD_FRONTMATTER_TIMESTAMP = "1970-01-01T00:00:00.000Z";

// Build the deterministic `lyt-scaffold: true` frontmatter block prepended to
// the priming seed files. Frontmatter ALWAYS flows through buildFrontmatter
// (the single SoT) — never hand-rolled here.
function scaffoldFrontmatter(title: string, purpose: string): string {
  return buildFrontmatter({
    title,
    created: SCAFFOLD_FRONTMATTER_TIMESTAMP,
    modified: SCAFFOLD_FRONTMATTER_TIMESTAMP,
    tags: [],
    purpose,
    topic: "scaffold",
    lytScaffold: true,
  });
}

export interface LytOverviewInput {
  vaultName: string;
  desc: string | null | undefined;
  owner: string;
}

// UNIT 2 — lyt-overview body is externalized to `templates/lyt-overview.md`.
// Per-template variable manifest: { vaultName, descBlock, owner }.
//   - descBlock: the author's `desc` when present, else the "(Add a
//     description…)" placeholder. render() has no conditionals by design, so the
//     caller resolves the branch and passes the final block.
// v1.D.5 `## Vault Primer` transclusion (`![[.lyt/primers/vault-primer]]`) lives
// statically in the template after `## Mesh Context`.
export function getLytOverviewContent(input: LytOverviewInput): string {
  const desc = (input.desc ?? "").trim();
  const descBlock =
    desc.length > 0
      ? desc
      : `_(Add a description here. Lyt scaffolded this section once at \`lyt vault init\` and never touches it again — it is yours to evolve.)_`;
  // UNIT 1 (C2) — prepend the `lyt-scaffold: true` frontmatter (via the SoT
  // buildFrontmatter) so this Lyt-authored seed file is FTS/primer-excluded by
  // the g6 gate (util/indexable.ts SCAFFOLD_RE). Frontmatter NEVER goes through
  // render() — it flows through the single contract.ts SoT.
  const frontmatter = scaffoldFrontmatter(input.vaultName, "Lyt vault overview (scaffold seed)");
  const body = renderTemplate("lyt-overview.md", {
    vaultName: input.vaultName,
    descBlock,
    owner: input.owner,
  });
  return frontmatter + body;
}

export interface InstalledPatternSummary {
  id: string;
  name: string;
  version: string;
  verbIds: readonly string[];
  // Skill slugs that wrap this pattern's verbs (e.g., ["/lyt-plan", "/lyt-retro"]).
  // Optional — when omitted, the listing shows pattern + verbs without skill mapping.
  skills?: readonly string[] | undefined;
}

export interface AgentsMdInput {
  vaultName: string;
  // OPTIONAL — when present, the "Installed patterns + skills" section is populated
  // between the LYT_PATTERNS delimiters. When omitted/empty, the section shows the
  // empty-state placeholder.
  installedPatterns?: readonly InstalledPatternSummary[] | undefined;
}

export function getAgentsMdContent(input: AgentsMdInput): string {
  const patternsBlock = renderInstalledPatternsSection(input.installedPatterns);
  const primerBlock = renderInstalledPrimerSection(input.vaultName);
  // UNIT 1 (C2) — prepend the `lyt-scaffold: true` frontmatter (via the SoT
  // buildFrontmatter) so agents.md is FTS/primer-excluded by the g6 gate. The
  // marker-bounded regen (regenAgentsMd) replaces ONLY content between the
  // LYT_PATTERNS / LYT_PRIMER markers, so this leading frontmatter is preserved
  // on regen; the full-rewrite branch (markers absent) re-emits it here.
  const frontmatter = scaffoldFrontmatter(
    "Working with Lyt in this vault (for AI agents)",
    "Lyt agent onboarding (scaffold seed)",
  );
  // UNIT 2 — agents.md body is externalized to `templates/agents.md`.
  // Per-template variable manifest: { version, vaultName, primerBlock,
  // patternsBlock }. The marker-bounded LYT_PRIMER / LYT_PATTERNS sections
  // live statically in the template; their dynamic CONTENT (computed in TS
  // below) is injected as the primerBlock / patternsBlock variables. The
  // marker comments in the template MUST stay byte-identical to the exported
  // AGENTS_MD_*_BEGIN/END constants (the regen chokepoint locates them by these
  // literals).
  const body = renderTemplate("agents.md", {
    version: String(AGENTS_MD_TEMPLATE_VERSION),
    vaultName: input.vaultName,
    primerBlock,
    patternsBlock,
  });
  return frontmatter + body;
}

function renderInstalledPatternsSection(
  installed: readonly InstalledPatternSummary[] | undefined,
): string {
  if (!installed || installed.length === 0) {
    return `_(No patterns linked into this vault yet. Run \`lyt pattern list\` to see what's installed at \`~/lyt/patterns/\`, then \`lyt pattern link <name> --vault <this-vault>\` to link them. Or run \`lyt vault adopt <path>\` / \`lyt vault join <path>\` — both auto-rebuild symlinks for every installed pattern.)_`;
  }
  const lines: string[] = [];
  lines.push(`This vault has the following Lyt patterns linked at \`Patterns/\`:`, ``);
  for (const p of installed) {
    const verbs = p.verbIds.join(", ");
    if (p.skills && p.skills.length > 0) {
      lines.push(`- **${p.id}@${p.version}** (verbs: ${verbs}) → skills: ${p.skills.join(", ")}`);
    } else {
      lines.push(`- **${p.id}@${p.version}** (verbs: ${verbs})`);
    }
  }
  lines.push(
    ``,
    `Run \`lyt help patterns\` for the full pattern catalog. Run \`lyt pattern verbs <name>\` for a pattern's verb list.`,
  );
  return lines.join("\n");
}

// Regenerate ONLY the LYT_PATTERNS section of an existing agents.md, leaving the rest
// of the file (which the user may have edited) intact. If the markers aren't present
// (older v1 template), the entire file is rewritten via getAgentsMdContent.
export function regenInstalledPatternsSection(
  existingContent: string,
  vaultName: string,
  installed: readonly InstalledPatternSummary[],
): string {
  const beginIdx = existingContent.indexOf(AGENTS_MD_PATTERNS_BEGIN);
  const endIdx = existingContent.indexOf(AGENTS_MD_PATTERNS_END);
  if (beginIdx < 0 || endIdx < 0 || endIdx <= beginIdx) {
    return getAgentsMdContent({ vaultName, installedPatterns: installed });
  }
  const before = existingContent.slice(0, beginIdx + AGENTS_MD_PATTERNS_BEGIN.length);
  const after = existingContent.slice(endIdx);
  const middle = "\n" + renderInstalledPatternsSection(installed) + "\n";
  return before + middle + after;
}

// v1.D.5 — render the content of the `## Vault primer` section that lives
// between the LYT_PRIMER markers. The content is a static pointer to the
// `.lyt/primers/` directory + the `lyt primer` regen verb — the actual
// primer markdown lives in `.lyt/primers/{scope}-primer.md` and is
// transcluded into lyt-overview.md via `![[.lyt/primers/vault-primer]]`.
// Putting a pointer (not the full primer text) in agents.md keeps the
// file scannable for agents while preserving the SoT in the primer file.
function renderInstalledPrimerSection(vaultName: string): string {
  return [
    `_The primer files at \`.lyt/primers/\` hold hot keywords + active arcs + recent activity + top lanes for this vault and mesh. Read them as a fast on-ramp before deeper exploration._`,
    ``,
    `Regenerate with:`,
    ``,
    `- \`lyt primer --scope vault --target ${vaultName}\` → \`.lyt/primers/vault-primer.md\``,
    `- \`lyt primer --scope mesh --target <mesh-name>\` → \`<mesh-main-vault>/.lyt/primers/mesh-primer.md\``,
    `- \`lyt primer --scope federation\` → \`<federation-or-first-vault>/.lyt/primers/federation-primer.md\``,
  ].join("\n");
}

// v1.D.5 — regenerate ONLY the LYT_PRIMER section of an existing
// agents.md. Mirror of `regenInstalledPatternsSection`. If markers are
// absent (older v2 file), return the existing content UNCHANGED — do
// NOT surprise-edit user-edited agents.md by auto-injecting the new
// section (per "What was decided" §8 of the v1.D.5 brief + global
// Rule #9 don't-add-what-wasn't-asked).
//
// To opt an existing v2 file into v3, either delete `agents.md` (next
// regen recreates from the v3 template via getAgentsMdContent) or hand-
// edit the file to include the LYT_PRIMER markers around an empty
// section (next regen populates).
export function regenInstalledPrimerSection(existingContent: string, vaultName: string): string {
  const beginIdx = existingContent.indexOf(AGENTS_MD_PRIMER_BEGIN);
  const endIdx = existingContent.indexOf(AGENTS_MD_PRIMER_END);
  if (beginIdx < 0 || endIdx < 0 || endIdx <= beginIdx) {
    return existingContent;
  }
  const before = existingContent.slice(0, beginIdx + AGENTS_MD_PRIMER_BEGIN.length);
  const after = existingContent.slice(endIdx);
  const middle = "\n" + renderInstalledPrimerSection(vaultName) + "\n";
  return before + middle + after;
}

// UNIT 2 — notes/index.md body externalized to `templates/notes-index.md`.
// Per-template variable manifest: { vaultName }. This seed is excluded from FTS
// by the isScaffoldNote BASENAME gate (index.md), so it intentionally carries
// NO lyt-scaffold frontmatter — its body has no frontmatter at all.
export function getNotesIndexContent(vaultName: string): string {
  return renderTemplate("notes-index.md", { vaultName });
}
