/*
 * Copyright 2026 MARLINK TRADING SRL (YounndAI)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Lane V Workstream 2 — `lyt bench` E-lite: IR metrics.
//
// Graded-relevance scoring ported faithfully from the validated research scorer
// (tools/lane-v/ir-scorer.mjs): nDCG@k, recall, MRR, P@1, plus a trap (planted
// false-positive) count for the content-hygiene signal nDCG can't see. The
// graded oracle is generated BY CONSTRUCTION (graded-corpus.ts), so there is no
// author-as-verifier bias — relevance is defined at generation time, not judged
// after seeing the rankings.

import type { SearchResult } from "@younndai/lyt-vault";

export const NDCG_K = 10;

// dcg = Σ (2^grade − 1) / log2(rank + 1) — matches ir-scorer.mjs:54.
export function dcg(grades: readonly number[]): number {
  return grades.reduce((acc, g, i) => acc + (Math.pow(2, g) - 1) / Math.log2(i + 2), 0);
}

export function round3(x: number): number {
  return Number.isFinite(x) ? Number(x.toFixed(3)) : 0;
}

export interface GradedQuery {
  id: string;
  query: string;
  scope: "federation" | "vault" | "mesh";
  scopeTarget?: string;
  // vault-relative path suffix → graded relevance (>=1 relevant; absent = 0).
  grades: Record<string, number>;
  // path suffixes that must NOT appear (planted false-positives / hygiene traps).
  traps?: string[];
}

export interface GradedQueryScore {
  id: string;
  query: string;
  nResults: number;
  recall: number;
  mrr: number;
  ndcg: number;
  pAt1: number;
  trapHits: number;
}

export function scoreGradedQuery(
  q: GradedQuery,
  results: readonly SearchResult[],
): GradedQueryScore {
  const relevantSuffixes = Object.keys(q.grades);
  const gradeOf = (path: string): number => {
    for (const suffix of relevantSuffixes) {
      if (path.endsWith(suffix)) return q.grades[suffix] ?? 0;
    }
    return 0;
  };

  // Dedup by figment path (keep first occurrence), preserving rank order.
  const seen = new Set<string>();
  const ranked: { path: string; grade: number }[] = [];
  for (const r of results) {
    if (seen.has(r.figment_path)) continue;
    seen.add(r.figment_path);
    ranked.push({ path: r.figment_path, grade: gradeOf(r.figment_path) });
  }
  const grades = ranked.map((x) => x.grade);

  const retrievedRel = new Set(
    ranked
      .filter((x) => x.grade >= 1)
      .map((x) => relevantSuffixes.find((s) => x.path.endsWith(s)) ?? x.path),
  );
  const recall = relevantSuffixes.length ? retrievedRel.size / relevantSuffixes.length : 0;

  const firstRelIdx = grades.findIndex((g) => g >= 1);
  const mrr = firstRelIdx >= 0 ? 1 / (firstRelIdx + 1) : 0;

  const idealGrades = relevantSuffixes.map((s) => q.grades[s] ?? 0).sort((a, b) => b - a);
  const idcg = dcg(idealGrades.slice(0, NDCG_K));
  const ndcg = idcg > 0 ? dcg(grades.slice(0, NDCG_K)) / idcg : 0;

  const firstGrade = grades[0] ?? 0;
  const pAt1 = firstGrade >= 1 ? 1 : 0;

  const traps = q.traps ?? [];
  const trapHits = ranked.filter((x) => traps.some((t) => x.path.endsWith(t))).length;

  return {
    id: q.id,
    query: q.query,
    nResults: results.length,
    recall: round3(recall),
    mrr: round3(mrr),
    ndcg: round3(ndcg),
    pAt1,
    trapHits,
  };
}

export interface GradedAggregate {
  queries: number;
  ndcg: number;
  recall: number;
  mrr: number;
  pAt1: number;
  // total trap (planted false-positive) hits across all queries; 0 = clean.
  cleanliness: number;
}

export function aggregateGraded(scores: readonly GradedQueryScore[]): GradedAggregate {
  const n = scores.length;
  const mean = (sel: (s: GradedQueryScore) => number): number =>
    n ? round3(scores.reduce((a, s) => a + sel(s), 0) / n) : 0;
  return {
    queries: n,
    ndcg: mean((s) => s.ndcg),
    recall: mean((s) => s.recall),
    mrr: mean((s) => s.mrr),
    pAt1: mean((s) => s.pAt1),
    cleanliness: scores.reduce((a, s) => a + s.trapHits, 0),
  };
}
