/*
 * Copyright 2026 MARLINK TRADING SRL (YounndAI)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// v1.D.4 — primer-generator flow.
//
// Composes a deterministic agent-priming markdown file from already-shipped
// per-vault caches: lanes.db (v1.D.1b) + arcs.db (v1.D.2b) + provenance.db
// (v1.A.2c per-vault DB SPLIT). Query-LESS aggregation (unlike v1.D.3 search
// which is query-driven): top-N keywords by frequency × recency, active
// arcs by last_touched DESC, recent provenance (last N days), top lanes
// by mem_count.
//
// Scope semantics (mirrors search-cascade.ts):
// vault — single registered vault; writes to <vault>/.lyt/primers/vault-primer.md
// mesh — union of home_mesh_rid + mesh_vaults entries; writes to
// mesh's main vault's .lyt/primers/mesh-primer.md
// federation — per OD-4 default: federation-repo not shipped yet
// (v1.A.0 pending) so we emit a per-vault stub at
// <first-vault-by-name>/.lyt/primers/federation-primer.md
// with a `> [!warning]` callout noting the limitation.
// Full federation-repo write lands in v1.A.0 + v1.D.4d.
//
// Recency weighting (OD-6 default): per keyword, score = mem_count ×
// exp(-days_since_lane.last_built / HALF_LIFE_DAYS). HALF_LIFE_DAYS = 7
// is the named constant. The formula is exponential decay with a 7-day
// characteristic time (1/e ≈ 0.37 after 7 days); the constant name is
// retained verbatim from OD-6 phrasing even though the formula is NOT a
// strict mathematical half-life (which would require ln(2)/7 in the
// exponent). The unit test asserts "a recent tag outranks an older tag
// at same base count" — that property holds for any monotonic-decreasing
// weighting; choosing exp() over linear preserves room for future tuning.
//
// Markdown shape (OD-7 default — 5 sections + Generated by footer):
// # Primer: <scope-name>
// <!-- Generated by ... -->
// ## Vault identity
// ## Top keywords
// ## Active arcs
// ## Recent activity (last <N> days)
// ## Top lanes
// ---
// ## Generated by
//
// Atomic write (OD-8 default): tmp file in same directory → rename(2).
// `--dry-run` returns the rendered markdown in the result and SKIPS disk
// write entirely.
//
// Lock 0.3 deterministic output (OD-10): pin `nowIso` via the test seam +
// sort all aggregates deterministically (keywords: score DESC, keyword
// ASC; arcs: last_touched DESC, name ASC; provenance: ts DESC, idHex
// ASC; lanes: mem_count DESC, name ASC). Same vault state + same nowIso
// → byte-identical markdown.

import { existsSync, mkdirSync, renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import type { Client } from "@libsql/client";

import { closeRegistry, openRegistry } from "../registry/client.js";
import { listVaultsInMesh } from "../registry/mesh-vaults-repo.js";
import { getMeshByName, type MeshRow } from "../registry/meshes-repo.js";
import { getVaultByName, getVaultByRid, listVaults, type VaultRow } from "../registry/repo.js";
import { listArcs, type ArcRow } from "../registry/arcs-repo.js";
import { listLanes, listMembersByLane, type LaneRow } from "../registry/lanes-repo.js";
import {
  listRecentFigments,
  loadKeywordSignals,
  loadModifiedByPath,
  type KeywordSignal,
} from "../registry/figment-meta-repo.js";
import { closeVaultDb, openLytDbActionable, openProvenanceDb } from "../registry/vault-db.js";
import { enforceNotFrozen } from "../util/freeze-check.js";
import { uuid7BytesToHex } from "../util/uuid7.js";

export const HALF_LIFE_DAYS = 7;
const MS_PER_DAY = 86_400_000;

const DEFAULT_TOP_KEYWORDS = 20;
const DEFAULT_TOP_ARCS = 10;
const DEFAULT_PROVENANCE_DAYS = 7;
const MAX_RECENT_ACTIVITY_ENTRIES = 50;

export type PrimerScope = "vault" | "mesh" | "federation";

export interface PrimerGenerateArgs {
  scope: PrimerScope;
  scopeTarget?: string;
  topKeywords?: number;
  topArcs?: number;
  provenanceDays?: number;
  // Test / determinism seam. Defaults to new Date().toISOString().
  nowIso?: string;
  // When true, the flow renders + returns markdown but skips disk write.
  dryRun?: boolean;
  // Open-once seam (v1.A.5 CR-B1 pattern).
  registryDb?: Client;
}

export interface PrimerKeyword {
  keyword: string;
  // Score = sum-over-lanes(mem_count × exp(-days_since_last_built / HALF_LIFE_DAYS)).
  score: number;
  // Sum of mem_count across all lanes containing this keyword.
  totalMemCount: number;
  // ISO of the most recent last_built across lanes carrying this keyword.
  lastSeen: string;
}

export interface PrimerArc {
  name: string;
  category: string;
  lastTouched: string;
  vaultName: string;
  memberCount: number;
}

export interface PrimerActivity {
  ts: number;
  tsIso: string;
  targetType: string;
  targetId: string;
  src: string;
  vaultName: string;
  // Hex of the UUIDv7 BLOB primary key — used as a deterministic tie-breaker.
  idHex: string;
}

export interface PrimerLane {
  name: string;
  keywords: readonly string[];
  memCount: number;
  vaultName: string;
}

export interface PrimerGenerateResult {
  scope: PrimerScope;
  scopeTarget: string | null;
  primerPath: string;
  markdown: string;
  dryRun: boolean;
  vaultsScanned: readonly string[];
  topKeywords: PrimerKeyword[];
  topArcs: PrimerArc[];
  recentActivity: PrimerActivity[];
  topLanes: PrimerLane[];
  durationMs: number;
}

export async function generatePrimerFlow(args: PrimerGenerateArgs): Promise<PrimerGenerateResult> {
  const startedAt = Date.now();
  const nowIso = args.nowIso ?? new Date().toISOString();
  const nowMs = Date.parse(nowIso);
  if (Number.isNaN(nowMs)) {
    throw new Error(
      `primer-generator: invalid nowIso ${JSON.stringify(args.nowIso)} (not parseable as ISO 8601).`,
    );
  }
  const topKeywords = clampPositive(args.topKeywords ?? DEFAULT_TOP_KEYWORDS);
  const topArcs = clampPositive(args.topArcs ?? DEFAULT_TOP_ARCS);
  const provenanceDays = clampPositive(args.provenanceDays ?? DEFAULT_PROVENANCE_DAYS);
  const dryRun = args.dryRun === true;
  const provenanceCutoffMs = nowMs - provenanceDays * MS_PER_DAY;

  const callerSuppliedRegistry = args.registryDb !== undefined;
  const registryDb = args.registryDb ?? (await openRegistry());

  let perVault: VaultAggregates[];
  let writeAnchorVault: VaultRow;
  let primerFileName: string;
  try {
    const resolved = await resolveScopeContext(registryDb, args.scope, args.scopeTarget);
    if (resolved.vaults.length === 0) {
      throw new Error(
        `primer-generator: scope=${args.scope}${args.scopeTarget !== undefined ? ` --target ${args.scopeTarget}` : ""} resolved 0 vaults. Register at least one vault first via 'lyt vault init'.`,
      );
    }
    writeAnchorVault = resolved.writeAnchor;
    // hardening pass (fix-pass): the primer WRITE lands in the anchor vault's
    // .lyt/primers — gate the mutation at its destination (any scope).
    // dry-run primers stay available on a frozen vault (read-only).
    if (!dryRun) {
      await enforceNotFrozen(writeAnchorVault.path, writeAnchorVault.name);
    }
    primerFileName = `${args.scope}-primer.md`;
    perVault = await aggregatePerVault(resolved.vaults, provenanceCutoffMs);
  } finally {
    if (!callerSuppliedRegistry) await closeRegistry(registryDb);
  }

  const merged = mergeAggregates(perVault, nowMs);
  const topKeywordList = merged.keywords.slice(0, topKeywords);
  const topArcsList = merged.arcs.slice(0, topArcs);
  const recentActivityList = merged.recentActivity.slice(0, MAX_RECENT_ACTIVITY_ENTRIES);
  const topLanesList = merged.lanes.slice(0, topArcs);

  const scopeLabel = formatScopeLabel(args.scope, args.scopeTarget, writeAnchorVault);
  const isFederationStub = args.scope === "federation";

  const markdown = renderPrimerMarkdown({
    scope: args.scope,
    scopeLabel,
    writeAnchorVault,
    nowIso,
    provenanceDays,
    topKeywords: topKeywordList,
    keywordsAreFallback: merged.keywordsAreFallback,
    topArcs: topArcsList,
    recentActivity: recentActivityList,
    topLanes: topLanesList,
    isFederationStub,
    scopeTarget: args.scopeTarget,
  });

  const primersDir = join(writeAnchorVault.path, ".lyt", "primers");
  const primerPath = join(primersDir, primerFileName);
  if (!dryRun) {
    mkdirSync(primersDir, { recursive: true });
    atomicWriteFile(primerPath, markdown);
  }

  return {
    scope: args.scope,
    scopeTarget: args.scopeTarget ?? null,
    primerPath,
    markdown,
    dryRun,
    vaultsScanned: perVault.map((p) => p.vault.name),
    topKeywords: topKeywordList,
    topArcs: topArcsList,
    recentActivity: recentActivityList,
    topLanes: topLanesList,
    durationMs: Date.now() - startedAt,
  };
}

// ---------------------------------------------------------------------------
// Scope resolution
// ---------------------------------------------------------------------------

interface ResolvedScope {
  vaults: VaultRow[];
  // The vault whose .lyt/primers/ directory receives the file.
  writeAnchor: VaultRow;
}

async function resolveScopeContext(
  registryDb: Client,
  scope: PrimerScope,
  scopeTarget: string | undefined,
): Promise<ResolvedScope> {
  switch (scope) {
    case "vault": {
      if (scopeTarget === undefined) {
        throw new Error("primer-generator: scope=vault requires --target <vault-name>.");
      }
      const v = await getVaultByName(registryDb, scopeTarget);
      if (!v) {
        throw new Error(`primer-generator: no vault registered with name '${scopeTarget}'.`);
      }
      return { vaults: [v], writeAnchor: v };
    }
    case "mesh": {
      if (scopeTarget === undefined) {
        throw new Error("primer-generator: scope=mesh requires --target <mesh-name>.");
      }
      const mesh: MeshRow | null = await getMeshByName(registryDb, scopeTarget);
      if (!mesh) {
        throw new Error(`primer-generator: no mesh registered with name '${scopeTarget}'.`);
      }
      const all = await listVaults(registryDb);
      const homeMatch = all.filter(
        (v) => v.homeMeshRid !== null && equalBytes(v.homeMeshRid, mesh.rid),
      );
      const memberRows = await listVaultsInMesh(registryDb, mesh.rid);
      const memberByHex = new Set(memberRows.map((r) => r.vaultRidHex));
      const memberVaults = all.filter((v) => memberByHex.has(v.ridHex));
      const byHex = new Map<string, VaultRow>();
      for (const v of homeMatch) byHex.set(v.ridHex, v);
      for (const v of memberVaults) byHex.set(v.ridHex, v);
      const meshVaults = [...byHex.values()].sort(byNameAsc);
      const writeAnchor = await resolveMeshWriteAnchor(registryDb, mesh, meshVaults);
      return { vaults: meshVaults, writeAnchor };
    }
    case "federation": {
      // OD-4 default — federation-repo not shipped (v1.A.0 pending);
      // emit per-vault stub at first-vault-by-name with explicit warning.
      const all = [...(await listVaults(registryDb))].sort(byNameAsc);
      if (all.length === 0) {
        return {
          vaults: [],
          // Synthetic empty anchor — caller will throw on 0 vaults.
          writeAnchor: {
            rid: new Uint8Array(),
            ridHex: "",
            name: "",
            path: "",
            status: "active",
          } as unknown as VaultRow,
        };
      }
      return { vaults: all, writeAnchor: all[0]! };
    }
  }
}

async function resolveMeshWriteAnchor(
  registryDb: Client,
  mesh: MeshRow,
  meshVaults: readonly VaultRow[],
): Promise<VaultRow> {
  // Prefer the mesh's main vault when registered.
  if (mesh.mainVaultRid !== null) {
    const main = await getVaultByRid(registryDb, mesh.mainVaultRid);
    if (main !== null) return main;
  }
  // Fall back to the first member by name.
  if (meshVaults.length > 0) return meshVaults[0]!;
  throw new Error(
    `primer-generator: mesh '${mesh.name}' has no member vaults to write the primer into.`,
  );
}

// ---------------------------------------------------------------------------
// Per-vault aggregation
// ---------------------------------------------------------------------------

interface VaultAggregates {
  vault: VaultRow;
  lanes: LaneRow[];
  arcs: ArcRow[];
  arcMemberCountByRidHex: Map<string, number>;
  // Lane V 0.4 (V-F9): lane rid hex → most-recent member figment authored
  // (frontmatter modified) ISO. Decay recency reads this, not lane build-time.
  laneRecencyByRidHex: Map<string, string>;
  recentProvenance: PrimerActivity[];
  // V-C-1 SC3 option-b: per-figment topic/tags keyword signals, consumed ONLY
  // when no lane formed (the empty-keywords fallback).
  keywordSignals: KeywordSignal[];
}

async function aggregatePerVault(
  vaults: readonly VaultRow[],
  provenanceCutoffMs: number,
): Promise<VaultAggregates[]> {
  const out: VaultAggregates[] = [];
  for (const vault of vaults) {
    if (vault.status === "tombstoned") continue;
    // corrupt lyt.db → CorruptLytDbError naming `lyt reindex`, not raw.
    const lytDb = await openLytDbActionable(vault.path, vault.name);
    let provDb: Client | null = null;
    try {
      const lanes = await listLanes(lytDb);
      const arcs = await listArcs(lytDb);
      const arcMemberCountByRidHex = new Map<string, number>();
      for (const arc of arcs) {
        // listArcs already returned the rid; count its members via the same
        // open lytDb client to keep this single-connection per vault.
        const memberCount = await countArcMembers(lytDb, arc.rid);
        arcMemberCountByRidHex.set(bytesToHexLower(arc.rid), memberCount);
      }

      // Lane V 0.4 (V-F9) — per-lane authored recency = the most recent member
      // figment's frontmatter `modified` (via figment_meta + lane_members).
      // Keyword decay reads THIS, not lane build-time, so a fresh tag outranks
      // a stale one regardless of when the cache was last rebuilt.
      const modifiedByPath = await loadModifiedByPath(lytDb);
      // V-C-1 SC3 option-b: load the per-figment topic/tags keyword signals up
      // front (one table scan) — used only if the lane-derived keyword list is
      // empty (mergeAggregates decides; cheap to always load at v1 vault sizes).
      const keywordSignals = await loadKeywordSignals(lytDb);
      const laneRecencyByRidHex = new Map<string, string>();
      for (const lane of lanes) {
        const members = await listMembersByLane(lytDb, lane.rid);
        let maxIso: string | null = null;
        for (const m of members) {
          const iso = modifiedByPath.get(m.figmentPath);
          if (iso !== undefined && (maxIso === null || iso > maxIso)) maxIso = iso;
        }
        if (maxIso !== null) laneRecencyByRidHex.set(bytesToHexLower(lane.rid), maxIso);
      }

      provDb = await openProvenanceDb(vault.path);
      const provenanceActivity = await loadRecentProvenance(provDb, provenanceCutoffMs, vault.name);
      // Lane V 0.4 (V-F16) — recent activity also includes recently-AUTHORED
      // figments (frontmatter `modified` within the window): the authored-time
      // source the (empty) event ledger could not provide.
      const cutoffIso = new Date(provenanceCutoffMs).toISOString();
      const recentFigments = await listRecentFigments(
        lytDb,
        cutoffIso,
        MAX_RECENT_ACTIVITY_ENTRIES,
      );
      const figmentActivity: PrimerActivity[] = recentFigments.map((rf) => ({
        ts: Date.parse(rf.modifiedIso),
        tsIso: rf.modifiedIso,
        targetType: "note",
        targetId: rf.figmentPath,
        src: "figment",
        vaultName: vault.name,
        idHex: `fm:${rf.figmentPath}`,
      }));
      const recentProvenance = [...provenanceActivity, ...figmentActivity];

      out.push({
        vault,
        lanes,
        arcs,
        arcMemberCountByRidHex,
        laneRecencyByRidHex,
        recentProvenance,
        keywordSignals,
      });
    } finally {
      await closeVaultDb(lytDb);
      if (provDb !== null) await closeVaultDb(provDb);
    }
  }
  return out;
}

async function countArcMembers(lytDb: Client, arcRid: Uint8Array): Promise<number> {
  const res = await lytDb.execute({
    sql: "SELECT COUNT(*) AS n FROM arc_members WHERE arc_rid = ?",
    args: [arcRid],
  });
  const row = res.rows[0];
  if (row === undefined) return 0;
  return Number(row["n"] as number | bigint);
}

async function loadRecentProvenance(
  provDb: Client,
  cutoffMs: number,
  vaultName: string,
): Promise<PrimerActivity[]> {
  const res = await provDb.execute({
    sql:
      "SELECT id, ts, target_type, target_id, src FROM provenance" +
      " WHERE ts >= ? ORDER BY ts DESC LIMIT ?",
    args: [cutoffMs, MAX_RECENT_ACTIVITY_ENTRIES],
  });
  return res.rows.map((row) => {
    const ts = Number(row["ts"] as number | bigint);
    return {
      ts,
      tsIso: new Date(ts).toISOString(),
      targetType: String(row["target_type"]),
      targetId: String(row["target_id"]),
      src: String(row["src"]),
      vaultName,
      idHex: uuid7BytesToHex(row["id"] as Uint8Array | ArrayBuffer),
    };
  });
}

// ---------------------------------------------------------------------------
// Cross-vault merge + scoring
// ---------------------------------------------------------------------------

interface MergedAggregates {
  keywords: PrimerKeyword[];
  // V-C-1 SC3 option-b: true when `keywords` came from the figment topic/tags
  // FALLBACK (no lane formed), so the renderer can mark the section instead of
  // implying a real lane signal. False for the normal lane-derived path AND for
  // a genuinely empty pod (0 figments → 0 fallback signals → honest placeholder).
  keywordsAreFallback: boolean;
  arcs: PrimerArc[];
  recentActivity: PrimerActivity[];
  lanes: PrimerLane[];
}

function mergeAggregates(perVault: readonly VaultAggregates[], nowMs: number): MergedAggregates {
  // Keywords: per-keyword aggregate across all lanes across all vaults.
  interface KwAcc {
    score: number;
    totalMemCount: number;
    // ISO of the most recent last_built across contributing lanes (string
    // ASC comparison is correct for ISO 8601 timestamps).
    lastSeenIso: string;
  }
  const kwAcc = new Map<string, KwAcc>();
  for (const v of perVault) {
    for (const lane of v.lanes) {
      // Lane V 0.4 (V-F9): recency = the lane's most-recent member AUTHORED
      // time (frontmatter `modified`) when known, else fall back to cache
      // build-time. Reading authored-time makes a fresh tag outrank a stale
      // one — previously both decayed off the (identical) build timestamp.
      const recencyIso = v.laneRecencyByRidHex.get(bytesToHexLower(lane.rid)) ?? lane.lastBuilt;
      const recencyMs = Date.parse(recencyIso);
      const daysSinceLast = Number.isFinite(recencyMs)
        ? Math.max(0, (nowMs - recencyMs) / MS_PER_DAY)
        : 0;
      const recencyFactor = Math.exp(-daysSinceLast / HALF_LIFE_DAYS);
      const contribution = lane.memCount * recencyFactor;
      for (const k of lane.sourceKeywords) {
        const existing = kwAcc.get(k);
        if (existing === undefined) {
          kwAcc.set(k, {
            score: contribution,
            totalMemCount: lane.memCount,
            lastSeenIso: recencyIso,
          });
        } else {
          existing.score += contribution;
          existing.totalMemCount += lane.memCount;
          if (recencyIso > existing.lastSeenIso) {
            existing.lastSeenIso = recencyIso;
          }
        }
      }
    }
  }
  const keywords: PrimerKeyword[] = [];
  for (const [keyword, acc] of kwAcc) {
    keywords.push({
      keyword,
      score: acc.score,
      totalMemCount: acc.totalMemCount,
      lastSeen: acc.lastSeenIso,
    });
  }
  keywords.sort((a, b) => {
    if (a.score !== b.score) return b.score - a.score;
    return a.keyword < b.keyword ? -1 : a.keyword > b.keyword ? 1 : 0;
  });

  // V-C-1 SC3 option-b — keyword FALLBACK. When NO lane formed (the empty
  // keyword list), derive keywords from each figment's frontmatter topic/tags
  // (figment_meta) so a single/untagged capture still surfaces a topical signal.
  // The fallback NEVER overrides a non-empty lane signal (no V-C-1 regression):
  // it is gated strictly on `keywords.length === 0`. A genuinely empty pod
  // (0 figments → 0 signals) keeps the honest empty placeholder.
  let keywordsAreFallback = false;
  let outKeywords = keywords;
  if (keywords.length === 0) {
    const fbAcc = new Map<
      string,
      { figmentCount: number; fromTopic: boolean; lastSeenIso: string | null }
    >();
    for (const v of perVault) {
      for (const sig of v.keywordSignals) {
        const cur = fbAcc.get(sig.keyword);
        if (cur === undefined) {
          fbAcc.set(sig.keyword, {
            figmentCount: sig.figmentCount,
            fromTopic: sig.fromTopic,
            lastSeenIso: sig.lastSeenIso,
          });
        } else {
          cur.figmentCount += sig.figmentCount;
          cur.fromTopic = cur.fromTopic || sig.fromTopic;
          if (
            sig.lastSeenIso !== null &&
            (cur.lastSeenIso === null || sig.lastSeenIso > cur.lastSeenIso)
          ) {
            cur.lastSeenIso = sig.lastSeenIso;
          }
        }
      }
    }
    if (fbAcc.size > 0) {
      const fbEntries = [...fbAcc.entries()].map(([keyword, a]) => ({ keyword, ...a }));
      // Same determinism contract as the lane path: count DESC, topic-ahead-on-
      // ties (topic is the stronger signal), keyword ASC. Byte-identical output
      // for the same vault state.
      fbEntries.sort((a, b) => {
        if (a.figmentCount !== b.figmentCount) return b.figmentCount - a.figmentCount;
        if (a.fromTopic !== b.fromTopic) return a.fromTopic ? -1 : 1;
        return a.keyword < b.keyword ? -1 : a.keyword > b.keyword ? 1 : 0;
      });
      outKeywords = fbEntries.map((e) => ({
        keyword: e.keyword,
        score: e.figmentCount,
        totalMemCount: e.figmentCount,
        // No nowIso here (keeps mergeAggregates pure + deterministic on vault
        // state alone); an em-dash when no contributing figment carried a date.
        lastSeen: e.lastSeenIso ?? "—",
      }));
      keywordsAreFallback = true;
    }
  }

  // Arcs.
  const arcs: PrimerArc[] = [];
  for (const v of perVault) {
    for (const arc of v.arcs) {
      arcs.push({
        name: arc.name,
        category: arc.category,
        lastTouched: arc.lastTouched,
        vaultName: v.vault.name,
        memberCount: v.arcMemberCountByRidHex.get(bytesToHexLower(arc.rid)) ?? 0,
      });
    }
  }
  arcs.sort((a, b) => {
    if (a.lastTouched !== b.lastTouched) return a.lastTouched < b.lastTouched ? 1 : -1;
    return a.name < b.name ? -1 : a.name > b.name ? 1 : 0;
  });

  // Recent activity.
  const recentActivity: PrimerActivity[] = [];
  for (const v of perVault) {
    for (const e of v.recentProvenance) recentActivity.push(e);
  }
  recentActivity.sort((a, b) => {
    if (a.ts !== b.ts) return b.ts - a.ts;
    return a.idHex < b.idHex ? -1 : a.idHex > b.idHex ? 1 : 0;
  });

  // Lanes.
  const lanes: PrimerLane[] = [];
  for (const v of perVault) {
    for (const lane of v.lanes) {
      lanes.push({
        name: lane.name,
        keywords: lane.sourceKeywords,
        memCount: lane.memCount,
        vaultName: v.vault.name,
      });
    }
  }
  lanes.sort((a, b) => {
    if (a.memCount !== b.memCount) return b.memCount - a.memCount;
    return a.name < b.name ? -1 : a.name > b.name ? 1 : 0;
  });

  return { keywords: outKeywords, keywordsAreFallback, arcs, recentActivity, lanes };
}

// ---------------------------------------------------------------------------
// Markdown rendering
// ---------------------------------------------------------------------------

interface RenderArgs {
  scope: PrimerScope;
  scopeLabel: string;
  writeAnchorVault: VaultRow;
  nowIso: string;
  provenanceDays: number;
  topKeywords: readonly PrimerKeyword[];
  keywordsAreFallback: boolean;
  topArcs: readonly PrimerArc[];
  recentActivity: readonly PrimerActivity[];
  topLanes: readonly PrimerLane[];
  isFederationStub: boolean;
  scopeTarget: string | undefined;
}

function renderPrimerMarkdown(args: RenderArgs): string {
  const lines: string[] = [];
  lines.push(`# Primer: ${args.scopeLabel}`);
  lines.push("");
  lines.push(`<!-- Generated by \`lyt primer\` at ${args.nowIso}. Regenerate to refresh. -->`);
  lines.push("");

  if (args.isFederationStub) {
    lines.push("> [!warning] Federation-repo not shipped yet (v1.A.0 pending).");
    lines.push(
      "> This file is a per-vault stub written into the first-vault-by-name's `.lyt/primers/`.",
    );
    lines.push(
      "> Full federation aggregation across `~/lyt/pod/primers/` lands in v1.A.0 + v1.D.4d.",
    );
    lines.push("");
  }

  // ## Vault identity
  lines.push("## Vault identity");
  lines.push("");
  lines.push(`- **Vault**: ${args.writeAnchorVault.name}`);
  lines.push(
    `- **Scope**: ${args.scope}${args.scopeTarget !== undefined ? ` (--target ${args.scopeTarget})` : ""}`,
  );
  lines.push(`- **Generated**: ${args.nowIso}`);
  lines.push("");

  // ## Top keywords
  lines.push("## Top keywords");
  lines.push("");
  if (args.topKeywords.length === 0) {
    lines.push(
      "_(No keywords yet — run `lyt vault rebuild-lanes` to populate `.lyt/indexes/lanes.yon` first.)_",
    );
  } else {
    // V-C-1 SC3 option-b: when no lane formed, keywords come from the figment
    // topic/tags fallback — mark the section so the signal isn't mistaken for a
    // real lane cluster. (≥2 figments must share a tag to form a lane.)
    if (args.keywordsAreFallback) {
      lines.push(
        "_(Derived from figment topic/tags — no lanes yet; ≥2 figments must share a tag to form a lane.)_",
      );
      lines.push("");
    }
    lines.push("| Keyword | Score | Total mem | Last seen |");
    lines.push("|---|---|---|---|");
    for (const k of args.topKeywords) {
      lines.push(`| ${k.keyword} | ${formatScore(k.score)} | ${k.totalMemCount} | ${k.lastSeen} |`);
    }
  }
  lines.push("");

  // ## Active arcs
  lines.push("## Active arcs");
  lines.push("");
  if (args.topArcs.length === 0) {
    lines.push(
      "_(No arcs yet — run `lyt vault rebuild-arcs` to populate `.lyt/indexes/arcs.yon` first.)_",
    );
  } else {
    lines.push("| Arc | Category | Last touched | Members | Vault |");
    lines.push("|---|---|---|---|---|");
    for (const a of args.topArcs) {
      lines.push(
        `| ${a.name} | ${a.category} | ${a.lastTouched} | ${a.memberCount} | ${a.vaultName} |`,
      );
    }
  }
  lines.push("");

  // ## Recent activity (last N days)
  lines.push(`## Recent activity (last ${args.provenanceDays} days)`);
  lines.push("");
  if (args.recentActivity.length === 0) {
    lines.push(
      "_(No provenance entries in this window — `provenance.db` is empty or all entries are older than the window.)_",
    );
  } else {
    lines.push("| Time | Target | Source | Vault |");
    lines.push("|---|---|---|---|");
    for (const r of args.recentActivity) {
      lines.push(
        `| ${r.tsIso} | ${r.targetType}:${truncate(r.targetId, 60)} | ${r.src} | ${r.vaultName} |`,
      );
    }
  }
  lines.push("");

  // ## Top lanes
  lines.push("## Top lanes");
  lines.push("");
  if (args.topLanes.length === 0) {
    lines.push(
      "_(No lanes yet — run `lyt vault rebuild-lanes` to populate `.lyt/indexes/lanes.yon` first.)_",
    );
  } else {
    lines.push("| Lane | Keywords | Members | Vault |");
    lines.push("|---|---|---|---|");
    for (const l of args.topLanes) {
      lines.push(`| ${l.name} | ${l.keywords.join(", ")} | ${l.memCount} | ${l.vaultName} |`);
    }
  }
  lines.push("");

  lines.push("---");
  lines.push("");
  lines.push("## Generated by");
  lines.push("");
  const cmdParts = [`lyt primer --scope ${args.scope}`];
  if (args.scopeTarget !== undefined) cmdParts.push(`--target ${args.scopeTarget}`);
  lines.push(`\`${cmdParts.join(" ")}\` at ${args.nowIso}`);
  lines.push("");
  return lines.join("\n");
}

function formatScopeLabel(
  scope: PrimerScope,
  scopeTarget: string | undefined,
  writeAnchor: VaultRow,
): string {
  if (scopeTarget !== undefined) return scopeTarget;
  if (scope === "federation") return "federation";
  return writeAnchor.name;
}

function formatScore(n: number): string {
  if (n === 0) return "0";
  if (n >= 100) return n.toFixed(0);
  if (n >= 10) return n.toFixed(1);
  return n.toFixed(2);
}

function truncate(s: string, n: number): string {
  if (s.length <= n) return s;
  return s.slice(0, n - 1) + "…";
}

// ---------------------------------------------------------------------------
// Atomic write
// ---------------------------------------------------------------------------

function atomicWriteFile(targetPath: string, contents: string): void {
  const tmpPath = `${targetPath}.${process.pid}-${tmpCounter()}.tmp`;
  writeFileSync(tmpPath, contents, "utf8");
  // On POSIX rename(2) is atomic; on Windows NTFS rename within the
  // same directory is metadata-only and atomic via MoveFileEx.
  renameSync(tmpPath, targetPath);
}

let tmpCounterValue = 0;
function tmpCounter(): number {
  tmpCounterValue += 1;
  return tmpCounterValue;
}

// ---------------------------------------------------------------------------
// Util
// ---------------------------------------------------------------------------

function clampPositive(n: number): number {
  if (!Number.isFinite(n) || n < 1) return 1;
  return Math.floor(n);
}

function byNameAsc(a: VaultRow, b: VaultRow): number {
  return a.name < b.name ? -1 : a.name > b.name ? 1 : 0;
}

function bytesToHexLower(b: Uint8Array): string {
  return Array.from(b)
    .map((n) => n.toString(16).padStart(2, "0"))
    .join("");
}

function equalBytes(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) return false;
  }
  return true;
}

// Silence unused-import lint when existsSync isn't referenced; the
// import lives for forward symmetry with other flow files that probe
// for the .lyt/ directory pre-write. Tree-shaken at build time.
void existsSync;
